version: "3"
services:
  linux:
    container_name: "ubuntu-linux"
    image: "mediasoup-ubuntu"
    restart: always
    tty: true
    ports:
      - "3000:3000"
      - "2000-2020:2000-2020"
      # - "10000-10100:10000-10100"
    volumes:
      - "./src:/usr/src"
